name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@1.0.2
        with:
            github_token: ${{ secrets.REPO_TOKEN }}
            version_files: 'Graph.UserInfo.Library/Graph.UserInfo.Library.csproj'
            patch: true
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Graph.UserInfo.Library/Graph.UserInfo.Library.csproj
          
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
