name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Bump versions
        uses: KageKirin/bump-csproj-version@v0.0.1
        with:
            file: 'Graph.UserInfo.Library/Graph.UserInfo.Library.csproj'
            patch: true
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Graph.UserInfo.Library/Graph.UserInfo.Library.csproj
          
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
